import { Inter } from "next/font/google";
import { Luckiest_Guy } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/context/ContextProvider";

const inter = Inter({ subsets: ["latin"] });
const LuckiestGuy = Luckiest_Guy({subsets: ["latin"], weight: ["400"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${LuckiestGuy.className}`}>
        <GlobalProvider>
        {children}
        </GlobalProvider>
        </body>
    </html>
  );
}
